name: Documentation
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
  pull_request:
    paths:
      - "docs/**"
      - "pyproject.toml"
      - ".github/workflows/docs.yaml"

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - name: Start UV install
        run: |
          sudo snap install --classic astral-uv --no-wait
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Finish UV install
        run: |
          sudo snap watch --last=install
      - name: Lint docs
        run: |
          make lint-docs
      - name: Build docs
        run: |
          make docs
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/
